version: '2'
services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8080:8080
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: reverseproxy:alpine
        restart: always
 
    node:
        depends_on:
            - reverseproxy
        image: tut83:latest
        ports:
            - 8081:8081
        restart: always
    
    bulletin:
        depends_on:
            - reverseproxy
        image: git:latest
        ports:
            - 8082:8082
        restart: always